services:
  - type: web
    name: mxone-api
    runtime: docker
    plan: free
    envVars:
      - key: BASE_URL
        value: http://10.105.64.17/GIT/Release/refs/tags/
      - key: MXONE_REMOTE_DIR
        value: /local/home/mxone_admin
